DROP TABLE IF EXISTS groups CASCADE;

DROP TABLE IF EXISTS students CASCADE;

DROP TABLE IF EXISTS courses CASCADE;

DROP TABLE IF EXISTS student_courses  CASCADE;

DROP TABLE IF EXISTS first_names;

DROP TABLE IF EXISTS last_names;